/**
 * test-s2.js — Verification Test Suite for S2 Wire Keenoc Calculator (#19)
 * Runs standalone using Node.js / Bun. Exits 0 on clean pass, 1 on failure.
 */

const assert = require('assert');
const { wireKeenocMounting } = require('./lib/keenoc-mounting-wire');

async function runTests() {
  console.log('🧪 [S2 Test] Starting test suite...');

  const mockCatalog = {
    'Mounting - Keenoc': [
      { 'รุ่น': 'Aluminum Rail 4200mm', 'ราคาขาย': '480' },
      { 'รุ่น': 'End Clamp 35mm', 'ราคาขาย': '38' },
      { 'รุ่น': 'Mid Clamp 35mm', 'ราคาขาย': '32' },
      { 'รุ่น': 'L-Feet 80mm', 'ราคาขาย': '48' }
    ]
  };

  // Test 1: Wire returns items generated by calculator
  const items = wireKeenocMounting(mockCatalog, 10, 'metal', () => []);
  assert.ok(items && items.length >= 4, 'Should return at least 4 items from calculator');
  assert.strictEqual(items[0].part_number, 'RAIL-4200', 'First item should be RAIL-4200');
  assert.strictEqual(items[0].quantity, 10, 'Rail quantity should be 10');

  // Test 2: Horus pattern — Fallback to legacy function if catalog is invalid/corrupt
  let fallbackCalled = false;
  const fallbackResult = wireKeenocMounting(null, 10, 'metal', () => {
    fallbackCalled = true;
    return [{ part_number: 'FALLBACK-RAIL', quantity: 10 }];
  });
  assert.strictEqual(fallbackCalled, true, 'Legacy fallback function should be called on invalid catalog');
  assert.strictEqual(fallbackResult[0].part_number, 'FALLBACK-RAIL', 'Fallback result should be returned');

  console.log('✅ [S2 Test] All 2 assertion checks PASSED cleanly!');
}

runTests().catch(err => {
  console.error('❌ [S2 Test] FAILED:', err);
  process.exit(1);
});
